version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: taskmanager-sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=TaskMgr#SecureP@ssw0rd2024!
      - MSSQL_PID=Developer
    ports:
      - "1433:1433"
    volumes:
      - sqlserver-data:/var/opt/mssql
    networks:
      - taskmanager-network
    healthcheck:
      test: /opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P TaskMgr#SecureP@ssw0rd2024! -C -Q "SELECT 1" || exit 1
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    container_name: taskmanager-backend
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=TaskManagerDb;User Id=sa;Password=TaskMgr#SecureP@ssw0rd2024!;MultipleActiveResultSets=true;TrustServerCertificate=True;Encrypt=True
      - Jwt__Key=ReplaceWithASecureRandomStringOfAtLeast32Chars!
      - Jwt__Issuer=TaskManagerAPI
      - Jwt__Audience=TaskManagerClients
      - Jwt__ExpiresDays=30
    ports:
      - "7195:80"
    depends_on:
      sqlserver:
        condition: service_healthy
    networks:
      - taskmanager-network
    restart: unless-stopped

  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
      args:
        - API_URL=http://localhost:7195
    container_name: taskmanager-frontend
    ports:
      - "4200:80"
    depends_on:
      - backend
    networks:
      - taskmanager-network
    restart: unless-stopped

networks:
  taskmanager-network:
    driver: bridge

volumes:
  sqlserver-data:
